language: go
go:
  - 1.5
  - tip

install:
  - go get github.com/tools/godep
  - go get github.com/smartystreets/goconvey

script:
  - GO15VENDOREXPERIMENT=1 godep go test $(go list ./... | grep -v /vendor/)
