language: go
go:
  - 1.5
  - tip

before_install:
  - brew install glide

install:
  - go get github.com/smartystreets/goconvey
  - glide install

script:
  - GO15VENDOREXPERIMENT=1 godep go test $(glide novendor)
